### ISSUE TITLE
Set up Project Board

### ISSUE THREAD

**Issue by vicmaburrito** [vicmaburrito/Space-Travelers-Hub#29]
[Project](https://github.com/vicmaburrito/Space-Travelers-Hub/projects/1)
- We're 2 in the team
- Anja and Manuel

**Comment by D4nielJ** [comment]
## Hello @vicmaburrito and @Anjacodes, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://c.tenor.com/HqR3cqZjITUAAAAM/sheldon-the-big-bang-theory.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
